### PR TITLE
Fix #127 RouteDomain,Address inconsistency

### LINKED ISSUE #127: RouteDomain and Address param [in]consistency
### Route Domain
#108 reveals that F5 IP Address fields can optionally include a [Route Domain](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-ip-routing-administration-11-2-0/2.html) suffix (i.e. %1, %4), which is currently not supported by System.Net.IPAddress.

### Address Parameter [In]Consistency
Currently, some functions (Get-PoolMember) declare Address as string[] and others (Add-PoolMember) as IPAddress[] (and Add-PoolMember now has a separate RouteDomain parameter). Instead, we should utilize a single param of a custom type which is composed of an IPAddress and a RouteDomain.

### ComputerName [In]Consistency
Some Functions have an explicit ComputerName param, others apply a ComputerName alias to Address, still others apply a ComputerName alias to Name.

### PR DESCRIPTION
**Pull request by vercellone**
I used C# to define a PoshLTM.F5Address type (struct) which is composed
of a ComputerName, IPAddress and RouteDomain.  GetHostAddresses
functionality has been encapsulated in the new struct.  This adds
support for computername and routedomain throughout the module without
the redundant supporting conditional logic in each Function affected.

### CODE REVIEW

**Comment by joel74** [comment]
With these changes, when I attempt to add a new member to a pool, the function now expects both a pool name and a pool object. It should only require one or the other.

**Comment by vercellone** [comment]
Glad you caught that.  I did run my Pester tests but I still haven't created tests for most Add/New/Remove/Set-* functions.  ParameterSetName corrections have been committed.

**Comment by joel74** [comment]
Thanks. I'm now getting the slightly more cryptic error below:

`Add-PoolMember -PoolName TEST_NA11 -Address 10.131.25.100 -PortNumber 80 -Status Disabled
`

Invoke-F5RestMethod : "400 Bad Request: A port number or service name is missing for "/@". Please specify a port number or service name using the syntax "/@:".

**Comment by vercellone** [comment]
There's a parameter binding problem.  Pipeline input is being bound to [string[]]$Name/PoolName instead of [PSObject[]]$InputObject which is causing raw JSON to be intjected into the URI.  I am considering removing ValueFromPipeline (or changing it to ValueFromPipelineByPropertyName) on the offending [string[]] params.

**Comment by joel74** [comment]
Cool. This looks like it fixes the Add-PoolMember issue. I'll do some more extensive testing first thing in the a.m.

**Comment by joel74** [comment]
On v11.6, Get-PoolMember isn't returning results for me. It's like when it internally calls Get-Pool and passes the pool object via the pipeline to Get-PoolMember, Get-PoolMember doesn't know that the object passed from the pipeline should be the InputObject. We get TRUE for the evaluation of "$null -eq $InputObject" and it grabs all the pools, cycles through them, and returns nothing. On v12.1, it works fine.

**Comment by vercellone** [comment]
I can't repo this on v11.5.1.  Can you provide more details?  What is Get-Pool returning?

If you rewrite Get-PoolMember to call itself with -InputObject explicitly instead of piping the Get-Pool output does that work?

**Comment by joel74** [comment]
Strange. I pulled down your fork again and retested, and it's not happening. Best I can figure is that maybe something didn't get unblocked / completely loaded the first time around, though no clue why it was only affecting v11.6. I'm good with merging, though I'm curious about the circumstances in which that object wouldn't get successfully piped.

**Comment by vercellone** [comment]
I just commited 5cb05a3 - Another F5Address comparsion correction.  The filters were not working for addresses containing a route domain, nor were they working when an [F5Address[]]$Address param contained more than one item.

I did some limited ad-hoc testing of *-Node and *-PoolMember, but I would feel better if @drryu and/or @elijahgagne could help verify the route domain functionality in their environments.

**Pull request merged**
