### PR TITLE
Rework for better pipeline support

### PR DESCRIPTION
**Pull request by vercellone**
1. try..catch refactored into Invoke-RestMethodOverride
2. Refactored where necessary to avoid Return statements
3. Added PSObject.typenames to facilitate formatting via TypeData\PoshLTM.Format.ps1xml
4. Deprecated Get-F5Session,Get-*List, Get-*Collection, and Get-PoolMember[Property] functions (they have not been removed yet, they just write warnings with the new equivalent command)
5. Minimized derived Urls in favor of F5Session.GetLink(selfLink)
6. First pass attempt to standardize parameter names
7. Pipeline-enabled most functions

These are ranked roughly by degree of potential controversy.  I'm anticipating a fair amount of discussion prior to acceptance.

### CODE REVIEW

**Comment by joel74** [comment]
At first glance, I think moving the try-catches into Invoke-RestMethodOverride is fine. Structurally and conceptually, not that big of a change. Avoiding Return statements - fine. 

I'm not sure why I should care about type data and the Add-ObjectDetail function seems to introduce an unnecessarily additional level of abstraction. I'll have be sold on that.

I currently don't want to deprecate the functions that return lists or collections. Specifically for pools and virtual servers, I don't want to have to return all properties of all objects, be they pools or virtual servers, just to get a list of names.

Transitioning from derived links to using self links is a good idea.

Let's continue the discussion.

Thanks,
Joel

**Comment by vercellone** [comment]
Excellent.  Just the formatting and deprecated functions in question then.

The typenames and Format.ps1xml control which properties Get-* functions display by default.  There is room for improvement, but i think they add a lot of value for nominal effort.  I encourage you to try them out.  I suspect you'll quickly realize the impact to usability.  And, I don't see any adverse impact in terms of abstraction.  If you do, please elaborate.

The deprecated functions were categorized as such based heavily upon [Don Jones' PowerShell Best Practices # 12](http://windowsitpro.com/blog/what-do-not-do-powershell-part-12) and [Strongly Encouraged Development Guidelines](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).  They probably fit better as helper functions in your profile, but if you prefer to maintain them, that's fine.

**Comment by vercellone** [comment]
I recalled the source of the [Add-ObjectDetail](https://raw.githubusercontent.com/RamblingCookieMonster/PSStash/master/PSStash/Private/Add-ObjectDetail.ps1) function.  It is another artifact shared by @RamblingCookieMonster in [Decorating PowerShell Objects](http://ramblingcookiemonster.github.io/Decorating-Objects/).  The function is overkill as implemented here since the same could be achieved with:

```PowerShell
[void]$object.PSObject.TypeNames.Insert(0,'PoshLTM.ObjectType')
```

My original thought was to use concrete types defined using C# POCOs, both for the formatting benefits and to facilitate strongly typed pipeline parameters.  Think [PoshLTM.Pool[]]$InputObject vs. [PSObject[]]$InputObject.  But, I'm worried that may prove too brittle for a possibly evolving REST API.  So, Add-ObjectDetail is a temporary compromise and placeholder.  I'm open to suggestions.

**Comment by joel74** [comment]
Ok, I'm definitely coming around to the commits I had some hesitations about. I didn't realize at first pass that Get-Pool, Get-PoolMember, Get-iRule would return the full collection of objects of the given type. Nice referencing the Don. Great guy, and I have yet to disagree with his PS advice. 

I think this would have been a bit more manageable had it been split up into separate issue and commits, but let's work with this. Let me poke around at the Add-ObjectDetail function for another day or two, make sure my head is completely wrapped around it. Thanks.

**Comment by vercellone** [comment]
I considered separating these into separate issues and commits after the fact.  1, 5, and 6 were useful if not necessary to deliver 7.  3 and 4 represent a logical next step that could have been separated.  2 should have been independent.  But, I took the easy way out.

**Comment by joel74** [comment]
Ok, let's do this. I'll clean up the Test-Functionality function soon, to not use the deprecated functions.

**Pull request merged**
