### PR TITLE
Fixes #30 address types must be the same IPv4/6

### LINKED ISSUE #30: Problem adding iRule to virtual server
I have a valid F5session variable, and 'Get-F5Status -F5Session $session' returns Active

When I run 'Add-iRuleToVirtualServer -F5Session $f5session -iRuleName '/BIS/Test' -VirtualServer '/BIS/DEV-WebServers.app/DEV-WebServers_vs' -Verbose' it returns:

VERBOSE: NB: Virtual server names are case-specific.
VERBOSE: GET https://f5.contoso.com/mgmt/tm/ltm/virtual/~BIS~DEV-WebServers.app~DEV-WebServers_vs with 0-byte payload
VERBOSE: received 2057-byte response of content type application/json
VERBOSE: NB: iRule names are case-specific.
VERBOSE: GET https://f5.contoso.com/mgmt/tm/ltm/rule/~BIS~Test with 0-byte payload
VERBOSE: received 174-byte response of content type application/json
VERBOSE: PUT https://f5.contoso.com/mgmt/tm/ltm/virtual/~BIS~DEV-WebServers.app~DEV-WebServers_vs?ver=12.0.0 with -1-byte payload
False

### PR DESCRIPTION
**Pull request by vercellone**
The source (::) and destination {ip} addresses for virtual server
{fullpath} must be be the same type (IPv4 or IPv6).

Use web -Method PATCH instead of PUT.  Applying to all of the following:
```PowerShell
Add-iRuleToVirtualServer
Add-PoolMonitor
Disable-PoolMember
Enable-PoolMember
Remove-iRuleFromVirtualServer
Remove-PoolMonitor
Set-PoolMemberDescription
```
Also including the following co-requisite bug fixes and enhancements
based on Pester tests in my environment:
```PowerShell
Add-PoolMonitor (Params, monitor manipulation)
Get-PoolMember (Params, IP, pipeline support)
Get-PoolMonitor (Params, Select monitor SilentlyContinue)
Remove-PoolMember (Params, remove by Adress OR Name)
Remove-PoolMonitor (Params, monitor manipulation)
```

### CODE REVIEW

**Comment by joel74** [comment]
Looks good. I like the param name clarification that's happening, in addition to the PATCH instead of PUT. 
So in Public/Remove-PoolMember.ps1, PortNumber was a leftover, unused param?

**Comment by vercellone** [comment]
Yes, PortNumber proved extraneous for the purpose of removing a pool member.

**Comment by vercellone** [comment]
I told you I had a lot of work in progress.  I hope everyone finds it as valuable as I have...

There is one known breaking change: 8ba52fe - If you have code that relies on Remove-* returning a boolean, that code will break.  I figured since Test-Functionality doesn't depend on it, it is probably safe.  I apologize in advance for any inconvenience.  But, I truly believe this is the typical and expected behavior of Remove-* cmdlets in general.

**Comment by dsolodow** [comment]
Might be best as a different PR, but it might be very useful to have your mentioned Pester tests for the module added to the repo.

**Comment by joel74** [comment]
A couple comments:
I'm not clear on what the benefit of Test-Pool, Test-VirtualServer and Test functions in general accepting an array of object is. That doesn't make sense to me.
Also I don't want to deprecate Get-CurrentConnectionCount. It's a very useful function and I don't want to have to replace it with a convoluted call to a pool member where I filter out the results to get the connections. What's the thinking behind wanting to deprecated it?

**Comment by vercellone** [comment]
Good questions.

#### Test-*
1. Test-Path was used as a guide; Return Trues and Falses through the pipeline.
1. Design Guidelines->Support Arrays for Parameters of  [Strongly Encouraged Development Guidelines](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx)

#### Get-PoolMemberStats 
1. Is included in 969e048 ( the one above titled Get-PoolMemberStats)
1. I'm OK with enhancing it to add a CurrentConnections alias property.  Until then, like the other deprecated functions, it is safe to call Get-CurrentConnectionCount directly.

**Comment by joel74** [comment]
Excellent. For some reason, when I looked through the changes previously, I didn't see Get-PoolMemberStats. 

Let's get this merged in, and then look at the alias properties. There are a few others I'd like to create aliases for as well. I'm thinking this will require modifications to the PostLTM.Format.ps1xml.

Thanks.

**Pull request merged**
