### PR TITLE
Added additional parameters and fixed issue with Add-PoolMonitors assigning only last monitor in the list.

### PR DESCRIPTION
**Pull request by koloss2001**
Added explicit type definition to the Add-PoolMonitors.ps1
Added Destination and Description parameters to the New-HealthMonitor.ps1
Added Monitor parameter to the New-Node.ps1

### CODE REVIEW

**Comment by joel74** [comment]
Hi, koloss2001, thanks for the pull request! The additional params look good. One suggestion for New-HealthMonitor is to add an example where description and destination are set. It might not be obvious to all that the IP address and port should be combined in Destination.

i.e. something like

.EXAMPLE
New-HealthMonitor -F5Session $F5Session -Name "/Common/test123" ...

New-HealthMonitor -F5Session $F5Session -Name "/Common/test_with_destination" -Type http -Description 'This is a test monitor' -Destination '192.168.1.100:80' -Receive '^HTTP.1.[0-2]\s([2|3]0[0-9])' -Send 'HEAD /host.ashx?isup HTTP/1.1\r\nHost: Test123.dyn-intl.com\r\nConnection: close\r\n\r\n'

Also, for New-Node, I couldn't get it to accept and set multiple monitors. When an array of monitors is passed in, it only adds the first to the new node. It's kind of strange that the monitor loop count is tied to the address array. What do you think is a good way to handle that - a separate loop? Thanks.

**Comment by koloss2001** [comment]
Hi Joel,

I have added additional examples to the New-HealthMonitor and fixed incorrect handling of Monitor parameter in New-Node.

**Comment by joel74** [comment]
Thanks. Looks great now. If you can just remove .vs/slnx.sqlite and .vs/ProjectSettings.json from the pull request, we'll be good to go and I can merge. Cheers.

**Comment by koloss2001** [comment]
Removed .vs/* files.

**Comment by joel74** [comment]
Thanks. Lets do this.

**Pull request merged**
