### PR TITLE
Profile HTTP for New-VirtualServer -ProfileNames

### PR DESCRIPTION
**Pull request by gamespirit**

### CODE REVIEW

**Comment by joel74** [comment]
Hi, gamespirit. Thanks for submitting this! After my first round of testing, it looks pretty good. 
I've only found a couple things so far:
1) If no profile name is passed to Get-ProfileHttp, I would expect it to return all HTTP profiles for the LTM. 
2) Get-ProfileHttp references "PoshLTM.Profil." Besides the typo, this type hasn't been created yet, and I would think we'd want to call it PoshLTM.ProfileHttp since the type and functions are specific to the HTTP profile.
Please let me know what you think.
Cheers,
Joel

**Comment by gamespirit** [comment]
Hi Joel, great idea.
May you change it or should I?
Haply Easter.

George

joel <notifications@github.com> schrieb am So., 1. Apr. 2018, 21:28:

**Comment by joel74** [comment]
Hi George,

The changes for 1) are pretty straight-forward, and you could easily add them to your pull request.
In Get-ProfileHttp.ps1, just change Mandatory from $true to $false for the $Name param and give it a default value of =''

For the change to 2) PoshLTM.Format.ps1xml, the question is what properties we want to include in the ProfileHTTP object. What do you think would be useful to include?

Thanks,
Joel

**Comment by gamespirit** [comment]
Hi Joel!

I asked my collage. His suggetion are these values.



I fixed your suggestions and commit to my repo.

How can I add my last commit to the pullrequest?



Mit besten  Grüßen,
Georg Aminger
----------------------------------------------------

2018-04-03 3:21 GMT+02:00 joel <notifications@github.com>:

**Comment by joel74** [comment]
Hi, Georg,
It looks like everything has been added / updated in your pull request, correct?
I'll check it out this evening and then should be able to merge.
Cheers,
Joel

**Comment by gamespirit** [comment]
Yes I added it. Great

joel <notifications@github.com> schrieb am Di., 3. Apr. 2018, 21:30:

**Comment by joel74** [comment]
Hi, Georg, I think what I'll do here is accept the pull request, and then open a new issue to resolve the outstanding params issues. I've figured out what the validation sets should be but I don't know the exact types for everything yet. There should be a way to grab the appropriate JSON from the logs.

**Comment by gamespirit** [comment]
Hi Joel!

I had no time to test it yesterday.
I plan todo it today and next week I plan to add profil-ssl-client freature.

Thanks for the merge.

Mit besten  Grüßen,
Georg Aminger
----------------------------------------------------

2018-04-05 5:59 GMT+02:00 joel <notifications@github.com>:

**Pull request merged**
