### PR TITLE
Fixes #86 Create Set-Pool 

### LINKED ISSUE #78: Can't get New-Pool with MemberDefinitionList parameter to work with existing nodes
When running the below command to create a new Pool with a node that already exists.

New-Pool -F5Session $F5Session -Name "TEST_POOL" -Partition "TEST" -MemberDefinitionList @("SERVERTEST,80")

Add-PoolMember : Cannot process argument transformation on parameter 'Address'. Cannot convert value "SERVERTEST" to type "System.Net.IPAddress". 
Error: "An invalid IP address was specified."
At C:\Program Files\WindowsPowerShell\Modules\F5-LTM\Public\New-Pool.ps1:49 char:90
+ ... ition -Address $Address -PortNumber 80 -Status "Enabled" -Name "SERVERTEST"
+                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PoolMember], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-PoolMember

### LINKED ISSUE #86: Create Set-Pool function to replace Set-PoolLoadBalancingMode and offer other functionality
We don't yet have a Set-Pool function and it would be good to have a general function that encompasses all that can be set on a pool.

### PR DESCRIPTION
**Pull request by vercellone**
Fixes #86 Create Set-Pool function to replace Set-LoadBalancingMode
Potentially fixes #78 New-Pool w/existing nodes

This does not fix $Address values of the form n.n.n.n%n.  But, New/Set-Pool -MemberDefinitionList does accept either computer names or ip addresses. 

New/Set-Pool use the fact that the first character of an ip address
always starts with a number and the first character of a computer name
does not.

### CODE REVIEW

**Comment by joel74** [comment]
This may unfortunately be a preexisting condition, but I can't get any of the Get-* commands to work, either with only a session passed in or with a name (pool name, virtual server, etc.). It seems that may have broken with the Invoke-F5RestMethod function was implemented. Jason, can you confirm? Thanks

**Comment by joel74** [comment]
Ok - figured out the auth error. Jason, when you created PR#92 and added Invoke-F5RestMethod,' you added the Credential property to all newly-created F5 sessions, even when a WebSession / auth token is used. Was that intentional? This causes an issue in Invoke-F5RestMethod, where there is an exclusive 'Either/Or' that first checks for $F5Session.Credential, and only if that's not found does it check for $F5Session.WebSession. So we never use the WebSession code in Invoke-F5RestMethod because all sessions have a Credential object.

Two ways to fix this:
1) Don't add the Credential property to F5 sessions that have a WebSession
2) In Invoke-F5RestMethod, change 'elseif ($F5Session.WebSession)'  to 'if ($F5Session.WebSession)'

I think my preference is for 2). Yours?

Also, we should either not try to force the error returned from Invoke-RestMethod into JSON, or we should first check whether if it can be converted to JSON. Otherwise we get a meaningless method about not being able to convert to JSON. Thoughts?

**Comment by joel74** [comment]
Notes on initial round of testing on Set-Pool
1) The examples are left over from Set-VirtualServer and don't apply to Set-Pool
2) It would be helpful to offer info / an example for how to structure MemberDefinitionList 
3) I'm not sure I follow the logic in the comment on ln 141:
"MemberDefinitionList should trump existing members IFF there is an ExistingPool, otherwise New-Pool will take care of initializing the members." Wouldn't we want to be able to pass in MemberDefinitionList to define the members of a new pool when calling Set-Pool?

**Comment by vercellone** [comment]
The intent was for $Credential to be $null for your WebSession scenario.  That is why I used an intermediate variable ($Credential) instead of $LTMCredentials directly. But, fix option 2 [if (WebSession)] is fine.

Checking whether the error can be converted to JSON sounds reasonable, and better than not converting at all.

**Comment by vercellone** [comment]
1. Yes.  I failed to update the examples I cut and paste from Set-VirtualServer.  Sorry.  You are welcome to update them or wait for me to get to it.
1. MemberDefinitionList is not my creation.  It is a holdover from the existing New-Pool function.  I am not happy with it because it doesn't allow referencing Nodes in other partitions.  Worthy of a separate issue, perhaps.
1. If there is no existing pool, then New-Pool will be called with -MemberDefinitionList included in the splatted parameters.  In that case, it would be redundant to remove and re-add the members.

**Comment by joel74** [comment]
Got it - thanks for clarifying. Would you prefer I submit changes as pull requests to your branch?

**Comment by vercellone** [comment]
Seems logical, but either way works for me.

**Pull request merged**
