### PR TITLE
Issue62

### PR DESCRIPTION
**Pull request by sanderma**
**new-virtualserver vlan parameter defaults to "disabled on"**

- Added logic to be able to tell if vlans should be allowed or disallowed. Defaults to allowed.
- Added whatif support.

### CODE REVIEW

**Comment by sanderma** [comment]
Noticed a setting I guess is a mistake?

[Parameter(**Mandatory=$true**,ParameterSetName = 'IpProtocol')]
[ValidateSet('tcp','udp','sctp')]
[Parameter(**Mandatory=$false**)]$ipProtocol=$null,

Didn't even know that was possible :)

**Comment by joel74** [comment]
Thanks, Sander. Good catch on the parameter settings discrepancy. We'll clean that up. 

I'm wondering about this setting to disable a VLAN on a new virtual server. It seems to only be applicable when one creates a default wildcard virtual server. From [here](https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/ltm_configuration_guide_10_1/ltm_virtual.html), I read:
"Note that a VLAN disabled list applies to default wildcard virtual servers only. You cannot create a VLAN disabled list for a wildcard virtual server that is associated with one VLAN only."

If I'm reading this correctly, the option to disable a specific VLAN is only applicable if the virtual server's destination IP is 0.0.0.0. Is that your understanding?

Cheers,
Joel

**Comment by sanderma** [comment]
Well, I saw that when I made a virtual server with my previous code, it was
made with the vlan enabled setting to "disabled on" ( in the GUI one item
above the vlan )
It seems the API doesn't have enabled as default for the setting.

Greets,
Sander

Op ma 10 okt. 2016 17:11 schreef joel <notifications@github.com>:

**Comment by joel74** [comment]
Got it. So the main win is setting this to EnabledOn by default. Makes sense and works for me.

**Comment by vercellone** [comment]
[Use Singular Parameter Names](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SD03)
[Parameters That Take True and False](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SD03)

I suggest:
```PowerShell
[switch]$DisableVlan
```

**Comment by sanderma** [comment]
The reason I did not use a bool, is because the setting in the GUI is like so:

image

It did not seem logical to set a DisableVlan to false to choose _enabled on_ vlan.
Moreso; there are three options:
- ALL VLANS and tunnels;
- Enabled on;
- Disabled on;

I made the parameter to reflect the GUI for ease of use.

I took the name of the parameter directly from the API reference:

image

But singular would be better perhaps yes.

**Comment by vercellone** [comment]
OK.  I see how using 2 different params might make sense.  Here are a couple alternatives to consider.

### 1 Enabled/Disabled param (could be a switch), 1 Vlan collection param
```PowerShell
        # 1) In the absence of either param enable for all Vlans
        # 2) Common ParameterSetName

        [cmdletbinding(SupportsShouldProcess = $True,DefaultParameterSetName='AllVlans')]
        ...
        [ValidateSet('Enabled','Disabled')]
        [Parameter(Mandatory=$false,ParameterSetName='Vlan')][string]$VlanTraffic='Enabled',
        [Parameter(Mandatory=$true,ParameterSetName='Vlan')][string[]]$Vlan,
```
### 2 mutually exclusive Vlan collection params
```PowerShell
        # 1) In the absence of either param enable for all Vlans
        # 2) Different ParameterSetName prevents specifying both

        [cmdletbinding(SupportsShouldProcess = $True,DefaultParameterSetName='AllVlans')]
        ...
        [Parameter(Mandatory=$false,ParameterSetName='DisableVlan')][string[]]$DisableVlan,
        [Parameter(Mandatory=$false,ParameterSetName='EnableVlan')][string[]]$EnableVlan,
```

I think the latter more clearly reflects the intent.

**Comment by joel74** [comment]
I've been working on a param set solution, but it's still complaining about being ambiguous. The solution I think we should shoot for is one where, if a -DisableVlan switch or an -EnableVlan switch is included, then a value for Vlan is required. If neither switch is set, then a value for Vlan cannot be passed in. We shouldn't default to enabling the Vlan.

**Comment by vercellone** [comment]
Including DefaultParamaterSetName in the cmdletbinding declaration is the key to avoiding ambiguity.

**Comment by joel74** [comment]
Thanks, Jason. I just realized that as well. 
I have a working param set, but it's very bulky:


```
  [cmdletbinding(SupportsShouldProcess=$True, DefaultParameterSetName='AllTunnelsAndVlans')]
      param (
        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$true)]$F5Session=$Script:F5Session,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)]$Kind="tm:ltm:virtual:virtualstate",

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Alias('VirtualServerName')]
        [Parameter(Mandatory=$true)][string]$Name,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)][string]$Partition,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)][string]$Description=$null,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$true)]$DestinationIP,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$true)]$DestinationPort,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)]$Source='0.0.0.0/0',

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)]$AllTunnelsAndVlansPool=$null,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)][string[]]$ProfileNames=$null,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$true,ParameterSetName = 'IpProtocol')]
        [ValidateSet('tcp','udp','sctp')]$ipProtocol=$null,

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)]$Mask='255.255.255.255',

        [Parameter(ParameterSetName=’AllTunnelsAndVlans’)]
        [Parameter(ParameterSetName=’DisableVlan’)]
        [Parameter(ParameterSetName=’EnableVlan’)]
        [Parameter(Mandatory=$false)]$ConnectionLimit='0',

        [Parameter(ParameterSetName=’DisableVlan’)]
        [switch]$DisableVlan,
	
        [Parameter(ParameterSetName=’EnableVlan’)]
        [switch]$EnableVlan,

        [Parameter(ParameterSetName=’DisableVlan’,Mandatory=$true)]
        [Parameter(ParameterSetName=’EnableVlan’,Mandatory=$true)]
        [string[]]$Vlan
    )

```

**Comment by vercellone** [comment]
The IpProtocol ParameterSetName is tripping you up, and doesn't appear to serve any useful purpose (making itself mandatory when it is specified? that is redundant unless I'm missing something).  If you remove it, you can reduce the rest to:

```PowerShell
  [cmdletbinding(SupportsShouldProcess=$True, DefaultParameterSetName='AllTunnelsAndVlans')]
      param (
        [Parameter(Mandatory=$true)]$F5Session=$Script:F5Session,

        [Parameter(Mandatory=$false)]$Kind="tm:ltm:virtual:virtualstate",

        [Alias('VirtualServerName')]
        [Parameter(Mandatory=$true)][string]$Name,

        [Parameter(Mandatory=$false)][string]$Partition,

        [Parameter(Mandatory=$false)]$Description=$null,

        [Parameter(Mandatory=$true)]$DestinationIP,

        [Parameter(Mandatory=$true)]$DestinationPort,
        [Parameter(Mandatory=$false)][string[]]$Vlans,
        [ValidateSet('vlansEnabled','vlansDisabled')]
        [Parameter(Mandatory=$false)][string]$VlansEnabledDisabled='vlansEnabled',
        [Parameter(Mandatory=$false)]$Source='0.0.0.0/0',

        [Parameter(Mandatory=$false)]$DefaultPool=$null,

        [Parameter(Mandatory=$false)][string[]]$ProfileNames=$null,

        [ValidateSet('tcp','udp','sctp')]$ipProtocol=$null,

        [Parameter(Mandatory=$false)]$Mask='255.255.255.255',

        [Parameter(Mandatory=$false)]$ConnectionLimit='0',

        [Parameter(ParameterSetName=’DisableVlan’)]
        [switch]$DisableVlan,

        [Parameter(ParameterSetName=’EnableVlan’)]
        [switch]$EnableVlan,

        [Parameter(ParameterSetName=’DisableVlan’,Mandatory=$true)]
        [Parameter(ParameterSetName=’EnableVlan’,Mandatory=$true)]
        [string[]]$Vlan
    )
```

But, I still think it needs refinement.

**Comment by vercellone** [comment]
My GUI may be different from yours, but it appears to me that the default is All VLANs and Tunnels.  Only when you are specifying one or more VLANs do you need to know whether to enable or disable for those VLANs.  So, my recommendation is:

```PowerShell
Function New-VirtualServer {
<#
.SYNOPSIS
    Create a new virtual server
#>
  [cmdletbinding(SupportsShouldProcess=$True, DefaultParameterSetName='AllTunnelsAndVlans')]
      param (
        [Parameter(Mandatory=$true)]$F5Session=$Script:F5Session,

        [Parameter(Mandatory=$false)]$Kind="tm:ltm:virtual:virtualstate",

        [Alias('VirtualServerName')]
        [Parameter(Mandatory=$true)][string]$Name,

        [Parameter(Mandatory=$false)][string]$Partition,

        [Parameter(Mandatory=$false)]$Description=$null,

        [Parameter(Mandatory=$true)]$DestinationIP,

        [Parameter(Mandatory=$true)]$DestinationPort,
        [Parameter(Mandatory=$false)]$Source='0.0.0.0/0',

        [Parameter(Mandatory=$false)]$DefaultPool=$null,

        [Parameter(Mandatory=$false)][string[]]$ProfileNames=$null,

        [ValidateSet('tcp','udp','sctp')]$ipProtocol=$null,

        [Parameter(Mandatory=$false)]$Mask='255.255.255.255',

        [Parameter(Mandatory=$false)]$ConnectionLimit='0',

        [Parameter(Mandatory=$false,ParameterSetName='DisableVlan')][string[]]$DisableVlan,
        [Parameter(Mandatory=$false,ParameterSetName='EnableVlan')][string[]]$EnableVlan
    )
        #...
        #Extra options for Vlan handling. Sets Vlans for VirtualServer, and sets it to be en- or disabled on those Vlans.
        If ($DisableVlan) {
            $JSONBody.vlans = $DisableVlan
            $JSONBody.vlansEnabled = $true
        } elseif ($EnableVlan) {
            $JSONBody.vlans = $EnableVlan
            $JSONBody.vlansDisabled = $true
        }
        #...
}
```

**Comment by sanderma** [comment]
We now have two (or perhaps even three) parameters for 1 option. I suggest
to keep it simple and use the validateset. We are not solving a problem by
introducing the switches.

It would only be logical if it would take away complexity elsewhere, which
it doesn't. The enable or disable can only be set if vlans are set, so it
only adds a difficult to read parameter subset.

Regards,
Sander.

Op wo 12 okt. 2016 00:23 schreef Jason Vercellone <notifications@github.com

**Comment by vercellone** [comment]
Switches have been ruled out because they require us to choose a default.  My understanding is that we do not want to assume enabled or disabled.  We want the user to be forced to indicate their preference.

```PowerShell
# Given that $vlans is a valid string array containing the desired VLANs...

## The ValidateSet option
New-Virtualserver -Vlan $vlans -VlanEnabledDisabled vlansEnabled
New-Virtualserver -Vlan $vlans -VlanEnabledDisabled vlansDisabled

## My recommendation: IMHO, this reduces complexity with no switches required.
New-Virtualserver -DisableVlan $vlans
New-Virtualserver -EnableVlan $vlans
 # Specifying both DisableVlan and EnableVlan together is not allowed.  It will throw a validation error.
New-Virtualserver -EnableVlan $vlans -DisableVlan $vlans
```

**Comment by sanderma** [comment]
I added the previous given suggestions.
Could you take a look?

**Comment by joel74** [comment]
I think it's looking a lot better. My comments to the latest revision are:
I'd prefer to have the Vlans param follow the standards and be the singular Vlan. 
I think instead of calling it VlanEnabledDisabled, we can call the param VlanState and have the validation set be Enabled and Disabled. Other than that, it looks good to me. Thanks.

**Comment by joel74** [comment]
Thanks, Sander. Looks good. Did you want to make a case for leaving the param name as Vlans instead of changing it to Vlan? I noticed that that wasn't changed.

**Comment by sanderma** [comment]
Nope, did the changes in a Train and forgot :/
I'll do it in a few hours

Op do 13 okt. 2016 18:21 schreef joel <notifications@github.com>:

**Comment by joel74** [comment]
Thanks. I believe there are still 2 more references to $Vlans that should be changed to $Vlan, and then we should be good.

**Comment by joel74** [comment]
Ok. We are very, very close here! I tested, and the one scenario that worked but probably shouldn't have is setting the Vlan state without including a value for Vlan. I found that if it is changed so 'Mandatory=$true' for the $Vlan param, then both $Vlan and $VlanState must have values, or neither have values, for the function call to execute.

**Comment by vercellone** [comment]
Neither of you feel that my recommendation reduces complexity?  If there are reasons it isn't a valuable or even viable option I would like to know for future reference.

```PowerShell
[Parameter(Mandatory=$false,ParameterSetName='DisableVlan')][string[]]$DisableVlan,
[Parameter(Mandatory=$false,ParameterSetName='EnableVlan')][string[]]$EnableVlan

New-Virtualserver -DisableVlan $vlans
New-Virtualserver -EnableVlan $vlans
```

**Comment by joel74** [comment]
I was initially thinking that setting both the Vlan values and their state in the same param wasn't ideal and it was better to have those in 2 separate params, but the more I think about it, I think I prefer the simplicity of your solution, Jason.  Sander, what do you think?

**Comment by sanderma** [comment]
I do like that it looks elegant. My standpoint was that they are two seperate things. A Vlan object and a seperate setting if they should be enabled or disabled.
It seems more clear that way what you are doing, like how the API is doing it.

It is not that I think it is a bad way of doing it at all!
It's just that I like to do it in roughly the same way as the API does it.

The only thing I can think of right now is if we ever use the pipeline to pass the vlans in, it would have to be a seperate parameter. I dont't see a usecase right now, but you never know...

**Comment by vercellone** [comment]
Regarding pipeline support: ValueFromPipelineByPropertyName would require both the name and the types to match.  The ValidateSet option fails on both counts.  I think the better choice in that regard is going to be an additional ValueFromPipeline $InputObject parameter: We're almost certainly going to need to go that route for future Set-* commands to support output from corresponding Get-* and New-* commands.

Is it valid to set vlansDisabled or vlansEnabled to true without also setting vlans or vice-versa?  If so, that requires separate parameters.  Otherwise, I don't see any value in separating them since they are codependent.

**Comment by joel74** [comment]
To answer your question, Jason - no, it's not valid to set vlansDisabled or vlansEnabled to true without also including a vlan value.

**Comment by vercellone** [comment]
I couldn't find any definitive guidance either way.  But, FWIW, the feedback I was able to gather has been in favor of simplicity over conforming to an API.  If you find something contradictory, please share it.

**Comment by sanderma** [comment]
Hi Joel, Jason,
I also had a couple of discussions about the issue, and a lot are in favour of simplicity.
I have been busy as of late and haven't looked into the issue for a while.
I've implemented the suggestion Jason made.
Best regards,
Sander.

**Comment by joel74** [comment]
Looks good, Sander. Thanks. 
I'm curious, though about the need for that first line 
`#requires -Version 3`
The entire module already requires V3 so this seems redundant.

Thanks,
Joel

**Comment by sanderma** [comment]
Jup, that was an oops. ISEsteroids checks the code, and does some best practices.
This one was redundant.
Removed the line

**Comment by joel74** [comment]
Looks good. Tested and works as expected. Jason, if you're good with this commit, I'll merge this. Thanks, guys.

**Comment by vercellone** [comment]
Looks good.  Merge as-is.

1 more nit picky comment: Powershell allows abbreviated parameter names until the parameter is no longer unambiguous.

I chose DisableVlan and EnableVlan instead of VlanDisable and VlanEnable with that fact in mind. It allows users to distinguish the parameters with fewer characters, while still allowing for auto-completion if you type -Vlan[Tab].  This is NOT a show stopper; use of abbreviations is considered bad practice anyway.  Just an editorial note.

```PowerShell
# DisableVlan and EnableVlan
New-VirtualServer -Di $vlans
New-VirtualServer -En $vlans

New-VirtualServer -DV $vlans
New-VirtualServer -EV $vlans

# VlanDisable and VlanEnable
New-VirtualServer -VlanD $vlans
New-VirtualServer -VlanE $vlans

New-VirtualServer -VD $vlans
New-VirtualServer -VE $vlans
```

**Comment by joel74** [comment]
Thanks, Jason. And thanks for all the effort, Sander.

**Comment by sanderma** [comment]
Hi Joel, Jason,

I also had a couple of discussions about the issue, and a lot are in favour
of simplicity.
I have been busy as of late and haven't looked into the issue, but I'll
update it today.
I'll implement the suggestion Jason made.

Best regards,
Sander.

Op do 20 okt. 2016 22:02 schreef Jason Vercellone <notifications@github.com

**Comment by sanderma** [comment]
Oops, that is isesteroids. It jams in best practices.

Op vr 21 okt. 2016 16:09 schreef joel <notifications@github.com>:

**Pull request merged**
