### PR TITLE
Default WarningAction set to 'SilentlyContinue' unless specifically provided

### PR DESCRIPTION
**Pull request by matthewjdegarmo**
Even upon successful session creation, users get a warning from the `ConvertTo-Json` cmdlet that reads:

```txt
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2.
```
This allows users to still provide a `-WarningAction` to `New-F5Session` which will be passed to the nested `ConvertTo-Json` cmdlets, but by default these will be suppressed.

### CODE REVIEW

**Comment by matthewjdegarmo** [comment]
It looks like this is no longer needed for PowerShell 7.2

See [Breaking Changes and Improvements](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-72?view=powershell-7.2#breaking-changes-and-improvements)

`Emit warning if ConvertTo-Json exceeds -Depth value (#13692)`

**Comment by thefirstnoe1** [comment]
I have tested and New-F5Session no longer gives the JSON warning.

**Comment by matthewjdegarmo** [comment]
This PR could be closed, unless we want to conditionally keep this suppressed warning on PSVersions -lt 7.2.0??

**Comment by joel74** [comment]
This all sounds good to me, @matthewjdegarmo . Thanks for doing the work. I'll go ahead and merge this.

**Pull request merged**
