### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by dsolodow**
Resolves issue #34

### CODE REVIEW

**Comment by vercellone** [comment]
Thanks, but I think you missed a bunch of new ones.  Also, please don't add the Private\*.ps1 ones to the readme.  I'll add another issue: Those are intended to be internal, not exported.

**Comment by dsolodow** [comment]
I've removed the private ones, and I saw one that I missed (inadvertently put one in twice). I compared the list of *.ps1 files in the public folder, as well as a get-command -module f5-ltm, so pretty sure I have them all. :)

**Comment by vercellone** [comment]
PR #33 hasn't been accepted yet.  To see the full list, refer to my fork at: [vercellone/POSH-LTM-Rest](https://github.com/vercellone/POSH-LTM-Rest/)

**Comment by vercellone** [comment]
Also note that Get-CurrentConnectionCount should be marked: deprecated.

**Comment by dsolodow** [comment]
Ah, I hadn't checked your fork. :)
So this PR is contingent on #33 being merged.

**Comment by vercellone** [comment]
Yes it is.

**Comment by vercellone** [comment]
Whoa!  Complete* and Get-Complete* are from Private\ArgumentCompletion.ps1, and therefore should not be included in the Readme.md.  They aren't intended to be called directly by end users.  They are loaded on import of the module, and allow tab completion of parameter values (i.e. Name, Partition, PoolName).  

You missed:Get-PoolMemberStats. joel mentioned I didn't include this in my PR.  Please check again.  If I missed it I'll commit it separately.

**Pull request merged**
