### PR TITLE
Create or overwrite iRules

### PR DESCRIPTION
**Pull request by sanderma**
Can create a new, and update an existing iRule.
Removes iRule from VirtualServers and adds them back again after uploading new iRule.
The command supports -whatif

### CODE REVIEW

**Comment by joel74** [comment]
Thanks, sanderma. I just tested this out and have a couple comments.
I'm not sure I see the need for the -PassThrough param. I like that a True or False is returned based on whether the iRule was successfully created or not. It seems confusing to return both True and the iRule if -PassThrough is enabled. I'd recommend continuing to use Get-iRule to return the iRule.

Also, if the iRule does not yet exist, the initial Get-iRule to check for it throws an error, and then the new iRule is created. We should suppress that error from Get-iRule. 

I realize that F5 uses 'apiAnonymous' as the param name for the body of the iRule, but that is not a helpful name. I'd recommend we either use a different param name, or assign an alias, like iRuleContent or something. 

Please let me know your thoughts. I like what you've done with this so far.

Cheers,
Joel

**Comment by sanderma** [comment]
Hi Joel,

You are right, I'll look into the passthrough. Didn't see that issue yet.
For the impossible strange param. I totally agree. nameiRuleContent it is. :D

Thank YOU for your work. It has been incredibly useful to work with. Happy to lend a hand.

Cheers!
Sander.

**Comment by joel74** [comment]
Looks good to me, Sander. Everything tested out okay, so I'm going to merge this.
One small comment for the future - it'd be helpful to have an issue to associate with a pull request. You could open an issue titled 'Need ability to set iRules', and then the conversation about it can be in there, and the pull requests can be associated with that issue. Make sense?
Cheers,
Joel

**Comment by sanderma** [comment]
Hi Joel,

Yeah it does, thnx. Just started using Github, and still finding my way around ;)
Thnx for merging btw.

Greets,
Sander.

**Comment by vercellone** [comment]
Nice contribution!  This module needs more Set-* commands like this.  Future enhancements to consider...

1. Refactor this into separate New-iRule and Remove-iRule commands.
1. Add SupportsShouldProcess support to all Add, Disable, Enable, New, Remove, and Set commands.

**Comment by sanderma** [comment]
Hi Jason,
Thnx!

I intentionally did not call the function New-iRule, because it can be annoying to check beforehand if a rule is already on the device or not.
Remove-iRule would be nice though yeah. If I remember correctly I've a script lying around that does exactly that. I need to remove them anyway, so when I implement it I'll create a pull request.

Greets,
Sander

**Comment by vercellone** [comment]
Please consider changing $Overwrite to $Force.  An Overwrite alias would be fine, but best practice is to use common parameter names.

**Pull request merged**
