### PR TITLE
Added support for Application parameter

### PR DESCRIPTION
**Pull request by elijahgagne**
I would very much appreciate someone else confirming that these changes don't break anything for them before this gets merged.

To support referencing iApps, I updated the Get-ItemPath function to take an optional parameter $Application. Functions that reference Get-ItemPath, but do not include $Application, should remain unchanged. 

I also added the $Application parameter to the following functions:
- Get-Pool
- Get-VirtualServer
- Enable-VirtualServer
- Disable-VirtualServer
- Test-Pool
- Test-VirtualServer

I imagine that there are other functions that could use this parameter, but I am not sure about any others at this time. For example, Get-iRule references Get-ItemPath, but I have never seen an iRule created inside an iApp.

Here are some examples using $Application:
```
Get-Pool -F5Session $F5Session -Name sharepoint-2010-bmr-443_pool -Application sharepoint-2010-bmr-443 -Partition dev

Get-VirtualServer -F5Session $F5Session -Name sharepoint-2010-bmr-443_http_virtual -Application sharepoint-2010-bmr-443 -Partition dev

Enable-VirtualServer -F5Session $F5Session -Name sharepoint-2010-bmr-443_http_virtual -Application sharepoint-2010-bmr-443 -Partition dev

Disable-VirtualServer -F5Session $F5Session -Name sharepoint-2010-bmr-443_http_virtual -Application sharepoint-2010-bmr-443 -Partition dev

Test-Pool -F5Session $F5Session -Name sharepoint-2010-bmr-443_pool -Application sharepoint-2010-bmr-443 -Partition dev

Test-VirtualServer -F5Session $F5Session -Name sharepoint-2010-bmr-443_http_virtual -Application sharepoint-2010-bmr-443 -Partition dev
```

### CODE REVIEW

**Comment by vercellone** [comment]
The good news is that existing functionality doesn't appear to be adversely impacted.  Here are the issues I've found:

- When specifying -Partition and -Application without also specifying -Name
  - (Dis|En)able-VirtualServer do nothing
  - Get-* functions filter by Partition only
  - Test-* functions: Name is mandatory, so it prompts for Name.

> Perhaps all of these should require Name, else we'll need to figure out how to filter by Application

- (Dis|En)able-VirtualServer outputs nothing.
  - Good: return a boolean indicating success or failure
  - Better: return the new state Enabled/Disabled
  - Best: return the updated VirtualServer object (we can update F5-LTM\TypeData\PoshLTM.Format.ps1xml to include the Enabled property in the default columns list)
- Alias('App') is redundant.  -App will already work without the alias.  You can remove that, or change it to iApp if desired.
- ArgumentCompletion functions for Application are needed.  Mostly a note to self, but you are welcome to tackle it if you are so inclined.

**Comment by vercellone** [comment]
> My F5's have iRules and HealthMonitors in iApps.  For example:

- iRule: /Production/exchange.[omitted].com.app/exchange.[omitted].com_snat_pool_iRule
- HealthMonitor: /Production/exchange.[omitted].com.app/exchange.[omitted].com_owa_https_monitor

**Comment by elijahgagne** [comment]
Thanks for the excellent feedback. 

1. What to do when $Name is null, but -Partition and -Application are non-null
    1. (Dis|En)able-VirtualServer: I'm inclined to make Name mandatory here
    1. Get-* function: I'm thinking that these should be updated to also filter by Application
    1. Test-* functions: I think it makes sense to leave things as is and prompt for Name
1. (Dis|En)able-VirtualServer outputs nothing
    1. I like what you've suggested for Best. I will work on implementing that.
1. Alias('App') is redundant.
    1. Thanks, I'll change the alias to iApp
1. ArgumentCompletion functions for Application are needed.
    1. Good note. If I get to the point that I am interested in working on this I'll shoot you a note to make sure you haven't already started.
1. iRule/monitor in iApp.
    1. I'll add support for Applications to these functions

I'll start work on 2i, 3i, and 5i. Do you agree with with my comments on 1i/ii/iii? If so, I'll work on those also.

**Comment by vercellone** [comment]
Sounds good for 1iii and 2-5.

Making Get-* filter by application will probably require client-side filtering.  Similar to the way [Get-PoolMember](https://github.com/joel74/POSH-LTM-Rest/blob/master/F5-LTM/Public/Get-PoolMember.ps1) does.

And, if you take that on, you might as well implement (Dis|En)able-VirtualServer like [Enable-PoolMember](https://github.com/joel74/POSH-LTM-Rest/blob/master/F5-LTM/Public/Enable-PoolMember.ps1).

If you'd rather: just make Name mandatory for the purpose of this issue, and create a new issue (enhancement) to add support for filtering by Application.

**Comment by elijahgagne** [comment]
I have updated my pull request to address items 2, 3, and 5. I will work on item 1, but I'd like to do that in a separate branch.

**Comment by joel74** [comment]
Looks good to me. Thanks, Elijah. Enable/Disable-VirtualServer returning updated objects as expected.
Re: making -Name mandatory, I can't think of a reason we wouldn't want to.
Cheers.

**Comment by elijahgagne** [comment]
Excellent. I will say that I have found some benefit from not making Name mandatory for the Get-* functions. In the case that Name is empty it becomes a wildcard and other filters are applied (e.g. Partition). Then I get back a collection of objects. That is useful if I want to see all the pools in the dev partition for example. 

But I am much more inclined to want Name mandatory on Test-* functions or functions that make a change. If Name is not mandatory there, I would worry about making changes to objects I didn't intent to. If I want to update multiple objects, the way I'd prefer to do it would be through the pipeline (e.g. `Get-Pool (filter here) | Enable-Pool`)

**Pull request merged**
