### PR TITLE
ScriptAnalyzer -Recurse

### PR DESCRIPTION
**Pull request by vercellone**
- Invoke-ScriptAnalyzer -Recurse (it was only analyzing the psd1 and psm1)
- Included changes to address most of the issues resulting from applying PSScriptAnalyzer recursively
- The remaining items were left to encourage discussion regarding the proper action.  Of course, if you don't agree with any of the changes I did include we can discuss those as well.

### CODE REVIEW

**Comment by joel74** [comment]
Looks good. A couple quick questions before merging the pull:
What's the thinking behind having the $null on the left of the equals instead of the right?
Could you add a few more notes to the Invoke-NullCoalescing function? I'm not familiar with c#'s ?? functionality. 
Also, do we not want the Remove-iRule function to return false if it fails? I though the standard was to return $true when a set-style function succeeds and $false when it fails.

Thanks.

**Comment by vercellone** [comment]
- Re: PSPossibleIncorrectComparisonWithNull: I have to defer to https://github.com/PowerShell/PSScriptAnalyzer/issues/477 and https://github.com/PowerShell/PSScriptAnalyzer/issues/200.  I was honestly tempted to suppress these, but I think that the intent of Invoke-NullCoalescing is clearer than the code it replaces.  It is more self documenting.
- Invoke-NullCoalescing works the same as C#'s [?? operator](https://msdn.microsoft.com/en-us/library/ms173224.aspx) and T-SQL's [COALESCE](https://msdn.microsoft.com/en-us/library/ms190349.aspx) function.  It simply returns the first non-null value, or null if all arguments are null.  I'll add something to this effect to the in-line help shortly.
- As part of PR #33 I updated all Remove-* functions to NOT return a boolean.  Instead they return nothing if all is well, and Write-Error if not while honoring $ErrorActionPreference.  Is it your opinion that Remove-iRule is more of a Set-* operation since it is patching virtualserver?  I don't think end users unfamiliar with the implementation would see it that way.

**Comment by joel74** [comment]
Thanks. I would think that any function that changes something would be considered a Set- operation, and we'd want to return TRUE or FALSE based on the result, but maybe that's not the correct pattern to be following.

**Comment by joel74** [comment]
It would have been cleaner if I had accepted this pull request before doing the rename.
I can reproduce the changes for this pull in a new commit, if that would be the easiest route forward. It wouldn't take that much.

**Comment by vercellone** [comment]
I believe the PowerShell standard is only for Test-* methods to return TRUE or FALSE.  Set-* methods return nothing unless you specify -PassThru which outputs a representation of the object created.  If you can find evidence to the contrary, please share it.

**Comment by vercellone** [comment]
Committed folder rename on my end.  Does that help at all?  If not, do whatever you've got to do to get the desired result.  I can manually sync after the fact if necessary.

**Comment by joel74** [comment]
Well, I think I botched that, and merged master into pr41, instead of the other way around.
Looking into that.

**Comment by joel74** [comment]
Should be good now. Working on automating module versioning so I can use Appveyor to auto-publish to PSGallery on commit.

**Comment by vercellone** [comment]
appveyor.yml line 12 and line 26 should take care of the module versioning.

12 version: 1.3.{build}
26 [-replace] "ModuleVersion = '.*'", "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'"

Is that not working properly?

**Comment by joel74** [comment]
I was attempting to test with the Publish-Module call directly. I'm not clear yet on how to test locally with an Appveyor.yml file, and I was hoping to do some local testing before updating the .yml file to publish.

**Comment by vercellone** [comment]
That makes sense.  For local testing just set the ModuleVersion and FunctionsToExport as desired in the manifest (F5-LTM.psd1) manually before executing Publish-Module.  Local testing of the appveyor.yml itself is not practical at this time.  Aside from basic syntax validation.

**Comment by vercellone** [comment]
Tip: Once you get Install-Module working properly with the psd1 edited manually, you could add -Verbose and __-Whatif__ to the appveyor.yml Install-Module command until that output looks good.  When all is well remove the -Whatif and optionally leave the -Verbose.

**Pull request merged**
